-- 0037_first_party_generated_assets.sql
--
-- WRITTEN, NOT APPLIED. Apply by hand in the Supabase SQL editor after review.
--
-- EXTENDS TWO ALLOWLISTS. WEAKENS NEITHER.
-- ========================================
-- drona-illustrations-v1 is 112 plates MonkLearning generated itself. Every row
-- carries:
--
--   licence     generated-free
--   source_url  generated:gemini:batch{N}/{asset_slug}
--   author      MonkLearning (AI-generated, Gemini)
--
-- and 0035 refuses all three: `generated-free` is not in the licence enum, and
-- `generated:...` is not an http(s) URL. Both refusals are CORRECT for the
-- content 0035 was written against, and both are wrong for this content — which
-- is the difference between a constraint that needs extending and one that
-- needs weakening.
--
-- WHY `generated-free` IS SAFE TO ADD, stated rather than assumed.
-- The licence enum exists to keep art we may not ship OUT: share-alike (CC
-- BY-SA, GFDL) and non-commercial (NC) are absent on purpose, and NCERT figures
-- are all-rights-reserved and deliberately have no member. Every one of those
-- risks is about THIRD-PARTY art and the terms its author attached.
--
-- This art has no third party. It was generated to our own prompts, from our
-- own work order, and MonkLearning owns the output outright — so there is no
-- share-alike clause to violate, no attribution to carry and no revocation to
-- fear. It is admitted as its own member rather than mapped onto CC0 for
-- exactly that reason: CC0 is a WAIVER a rightsholder grants, and recording a
-- waiver nobody executed would be a provenance field asserting something that
-- did not happen. `generated-free` says what is true.
--
-- WHY `generated:` IS SAFE TO ADD.
-- `source_url` exists so a row can be traced to where its art came from, and
-- the http(s) rule exists because "the archive.org page" cites nothing. A
-- generated asset has no page — its origin is a batch and a slug, and
-- `generated:gemini:batch4/bio11-ch4-...` is exactly as traceable as a URL:
-- it names the generator, the batch and the asset.
--
-- The pattern stays TIGHT rather than becoming "anything without spaces". It
-- admits one shape only, `generated:<tool>:<batch>/<slug>`, so a row cannot
-- smuggle prose through this column the way a bare NOT NULL would allow.

begin;

-- ── licence ────────────────────────────────────────────────────────────────
alter table public.concept_assets
  drop constraint if exists concept_assets_licence_enum;

alter table public.concept_assets
  add constraint concept_assets_licence_enum check (
    licence in (
      -- third-party, unchanged from 0035
      'CC0-1.0',
      'CC-BY-4.0',
      'CC-BY-3.0',
      'CC-BY-2.5',
      'PD-US-gov',
      'PD-old-70',
      -- first-party, generated to our own prompts. NOT a waiver; ownership.
      'generated-free'
    )
  );

-- ── source_url ─────────────────────────────────────────────────────────────
alter table public.concept_assets
  drop constraint if exists concept_assets_source_url_is_url;

alter table public.concept_assets
  add constraint concept_assets_source_url_is_url check (
    -- a real page, unchanged from 0035
    source_url ~ '^https?://[^[:space:]]+$'
    -- or a generated asset's origin: tool, batch, slug. Deliberately narrow —
    -- lowercase tool and batch, and a slug in the same alphabet
    -- concept_assets_slug_shape already enforces.
    or source_url ~ '^generated:[a-z0-9]+:[a-z0-9]+/[a-z0-9]+(-{1,2}[a-z0-9]+)*$'
  );

commit;

-- ------------------------------------------------------------- verification
--   -- the new licence is admitted and the old ones still are
--   select licence, count(*) from concept_assets group by 1 order by 2 desc;
--
--   -- nothing smuggled prose through source_url
--   select asset_slug, source_url from concept_assets
--    where source_url !~ '^https?://' and source_url !~ '^generated:';
--   -- (expect zero rows; the constraint makes it impossible, this proves it ran)
--
-- WHAT IS STILL REFUSED, and must stay refused:
--   licence 'CC-BY-SA-4.0'   share-alike
--   licence 'CC-BY-NC-4.0'   non-commercial
--   licence 'unknown'        the placeholder denylist catches it first
--   source_url 'generated by gemini'   prose, not an origin
--   source_url 'generated:gemini:batch1'  no slug — an origin that names no asset
